### ISSUE TITLE
Bad Drive Tuning

### ISSUE THREAD

**Issue by cuttestkittensrule** [Prospect-Robotics/Robot2024#43]
The Drive train was not tuned very well, so it should be improved

## To-Do List

- [ ] Find Max speed @ 12v
- [ ] Tune steer gains
- [ ] Tune drive gains
- [ ] Tune slip current
- [ ] Tune coupling gear ratio
